name: greedyFS
channels:
  - salilab
  - defaults
dependencies:
  - python=3.6.9
  - scikit-learn=0.21.1
  - seaborn=0.9.0
  - biopython=1.74
  - xgboost=1.4.2
  - pip:
    - freesasa==2.0.3.post6
    - terminalplot==0.2.6
    - yellowbrick==1.0.post1
